spring:
  application:
    name: coeuiservice

logging:
  level:
    com.coeui: INFO 
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level  - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file: /logs/coeuiservice.log 
  
